name: Deploy React App
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploying to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install packages
        run: npm i

      - name: Build production
        run: npm run build
